services:
    nginx:
        container_name: glpi_nginx
        image: nginx:stable-alpine
        restart: always
        ports:
          - 80:80
        volumes:
          - ./glpi.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - php
    php:
        container_name: glpi_php
        pull_policy: never
        build: .
        image: glpi_php
        restart: always
        user: 1000:1000
        volumes:
          - ./glpi.ini:/usr/local/etc/php/conf.d/glpi.ini:ro
          - ./glpi/:/var/www/glpi/:ro
          - ./config/:/etc/glpi/
          - ./plugins/:/var/lib/glpi/plugins/
          - ./files/:/var/lib/glpi/files/
          - ./logs/:/var/log/glpi/
        depends_on:
          - mariadb
    mariadb:
        container_name: glpi_mariadb
        image: mariadb:latest
        restart: always
        volumes:
          - ./mariadb/:/var/lib/mysql/:Z
          - ./glpi.sql:/docker-entrypoint-initdb.d/glpi.sql:ro
        environment:
            MARIADB_USER: glpi
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
            MARIADB_DATABASE: glpi
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
