#!/usr/bin/sh

# Copyright 2024, 2025 Prefeitura Municipal de Campo Largo <analistas@campolargo.pr.gov.br>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

VERSION=$(wget -q https://api.github.com/repos/glpi-project/glpi/releases/latest -O - | grep -m 1 '^  "tag_name": "' | cut -d '"' -f 4)
wget -q --show-progress https://github.com/glpi-project/glpi/releases/download/${VERSION}/glpi-${VERSION}.tgz
tar -zxf glpi-${VERSION}.tgz
rm glpi-${VERSION}.tgz
cp downstream.php glpi/inc/
cp local_define.php glpi/config/
mv glpi/config/ .
mv glpi/files/ .
mkdir plugins/
mkdir logs/
mkdir mariadb/
docker compose up -d --wait
echo 'Access the Web interface to complete installation'
read -p 'Web installation complete? [y/N]' yn

if [ "$yn" != y -a "$yn" != Y ]; then
    exit
fi

rm -rf glpi/install/
docker compose exec php php /var/www/glpi/bin/console database:enable_timezones
docker compose down
sed -i 's|/etc/glpi/$|/etc/glpi/:ro|' compose.yml
docker compose up -d --wait
sudo tee -a /etc/crontab > /dev/null << EOF
* * * * * $USER docker exec glpi_php php /var/www/glpi/front/cron.php > /dev/null 2>&1
EOF
